[package]
name = "gsp-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "gsp-bench"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
gsp-config = { path = "../gsp-config" }
gsp-core = { path = "../gsp-core" }

tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
socket2.workspace = true
