[package]
name = "wayhouse-controller"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "wayhouse_controller"
path = "src/lib.rs"

[[bin]]
name = "wayhouse-controller"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
wayhouse-http = { workspace = true, features = ["server"] }
wayhouse-config = { path = "../wayhouse-config" }
wayhouse-plugin-host = { path = "../wayhouse-plugin-host" }

sled.workspace = true
thiserror.workspace = true
tokio.workspace = true
axum.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
similar.workspace = true
reqwest.workspace = true
openraft = { version = "0.9.25", features = ["serde", "storage-v2"] }
async-trait.workspace = true
rand.workspace = true
base64 = "0.22"
chacha20poly1305 = "0.11"
sha2.workspace = true
zeroize = "1"
url = "2"

[dev-dependencies]
tempfile.workspace = true
wat.workspace = true
tower = "0.5"
